### ISSUE TITLE
post-fs-data

### ISSUE THREAD

**Issue by skittles9823** [SmartPack/ScriptManager#1]
Some boot scripts need to be loaded earlier than others, for example permissive bootscripts and sepolicy patches (although they're better as init scripts)

It would be nice to have a popup to set whether to make the bootscript run in post-fs-data mode (/data/adb/post-fs-data.d) or late-start mode (/data/adb/service.d).

**Comment by sunilpaulmathew** [comment]
> Some boot scripts need to be loaded earlier than others, for example permissive bootscripts and sepolicy patches (although they're better as init scripts)
> 
> It would be nice to have a popup to set whether to make the bootscript run in post-fs-data mode (/data/adb/post-fs-data.d) or late-start mode (/data/adb/service.d).

That's a great idea.
Will do it for sure...
Thanks a lot...

**Comment by sunilpaulmathew** [comment]
Dear @skittles9823 

The suggested changes are already made (b972c7ee7e2cdc4af48ad1c2e7bea9c17cdcccbd). If you have time, please have a look on the commit and suggest me any changes required (especially the choice words)?
Thanks in advance

Have a nice day
Sunil

**Comment by skittles9823** [comment]
Oof. Will check it out now.

**Comment by skittles9823** [comment]
Strings seem fine, scripts get copied to the correct dir fine 👌👌
