### ISSUE TITLE
Essential features

### ISSUE THREAD

**Issue by Uranya** [SmartPack/ScriptManager#5]
Dear friend,
how can I pass arguments to scripts?

Another useful feature would be adding schedules to scripts.

Thank you for your work!

**Comment by sunilpaulmathew** [comment]
I don't understand about the first part.
For the schedule, currently it is not planned because it need more complex work. At this moment, I am planing to maintain this app as simple as possible.

**Comment by Uranya** [comment]
Hi friend,
normally a script uses arguments, such as the function chmod 777 filename, that uses two arguments, the first is 777 and the second is filename.

Thanks for your fast reply!

**Comment by sunilpaulmathew** [comment]
> Hi friend,
> normally a script uses arguments, such as the function chmod 777 filename, that uses two arguments, the first is 777 and the second is filename.
> 
> Thanks for your fast reply!

You can add that (basically any terminal command) to the script.
