### ISSUE TITLE
Save Script Not Working

### ISSUE THREAD

**Issue by landry314** [SmartPack/ScriptManager#6]
When I make a script and then tap the disk icon in upper right it does nothing. It closes the script. I can't find the file I made in my files.

I am using Lineage OS 18.1 (Android 11) on a Pixel 3 and version 4.4 of ScriptManager.

**Comment by sunilpaulmathew** [comment]
Hi, have you check the folder **/sdcard/scripts/**. That is the place in which all the created/imported scripts are saved.

**Comment by landry314** [comment]
no scripts folder was made on my sdcard. i did a search at root for the files when i saved them. nothing was found. it seems the file creation is failing without an error message. this is likely because the app has no permissions and cant write outside of its data folder. it could write to the /sdcard/Android/data/ folder though without permission. Android 11 is tighter on permissions. you might want to request read/write to external storage permission... or fallback to /Android/data/ in case of failure.

**Comment by landry314** [comment]
or ask the user where he wants to save each file... or add a setting for a default folder

**Comment by sunilpaulmathew** [comment]
> s tighter on permissions. you might w

Most probably, this will be the issue. In order to test, can you manually create a folder "scripts" at internal sdcard and see the rest of the processes working. I'll try to migrate to /sdcard/Android/data/ (or in the worst case, app's files directory) to solve that issue. However, it will make some inconvenience for users. Thanks a lot for your inputs.

**Comment by landry314** [comment]
ok i tried creating /sdcard/scripts/ manually first. it still doesn't save the scripts anywhere.

**Comment by landry314** [comment]
And I think I know why... A permission finally showed up in the App info and it says "Allow access to media only". Material Files has the permission "Allow management of all files"...

![Screenshot_20210126-102827_Permission_controller](https://user-images.githubusercontent.com/6866501/105866326-e0379d00-5fc1-11eb-8909-4744000f4c4b.png)

**Comment by landry314** [comment]
Some changes to permissions have occurred in Android 11:
https://developer.android.com/about/versions/11/privacy/storage
